protected/modules/admin/controllers/ReplyController.php
<?php

class ReplyController extends AdminController
{

    /**
    * Displays a particular model.
    * @param integer $id the ID of the model to be displayed
    */
    public function actionView($id)
    {
        $model = $this->loadModel($id);
        if($model->type==Reply::TYPE_NEWS){
            $this->redirect(array('articleView', 'id'=>$id));
        }

        $this->render('view',array(
            'model'=>$model,
        ));
    }

    /**
    * Displays a particular model.
    * @param integer $id the ID of the model to be displayed
    */
    public function actionArticleView($id)
    {
        $this->render('articleView',array(
            'model'=>$this->loadModel($id),
        ));
    }

    /**
    * Creates a new model.
    * If creation is successful, the browser will be redirected to the 'view' page.
    */
    public function actionArticleCreate()
    {
        $model=new Reply('article');

        if(isset($_POST['Reply']))
        {
            $model->attributes=$_POST['Reply'];
            $model->type = Reply::TYPE_NEWS;
            if($model->save())
            {
                $this->redirect(array('articleView','id'=>$model->id));
            }
        }

        $this->render('articleCreate',array(
            'model'=>$model,
        ));
    }

    /**
    * Creates a new model.
    * If creation is successful, the browser will be redirected to the 'view' page.
    */
    public function actionCreate()
    {
        $model=new Reply();

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Reply']))
        {
            $model->attributes=$_POST['Reply'];
            if($model->save())
                $this->redirect(array('view','id'=>$model->id));
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    }

    /**
    * Updates a particular model.
    * If update is successful, the browser will be redirected to the 'view' page.
    * @param integer $id the ID of the model to be updated
    */
    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);

        if($model->type==Reply::TYPE_NEWS){
            $this->redirect(array('articleUpdate', 'id'=>$id));
        }

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Reply']))
        {
            $model->attributes=$_POST['Reply'];
            if($model->save())
            {
                $this->redirect(array('view','id'=>$model->id));
            }
        }

        $this->render('update',array(
            'model'=>$model,
        ));
    }

    /**
    * Updates a particular model.
    * If update is successful, the browser will be redirected to the 'view' page.
    * @param integer $id the ID of the model to be updated
    */
    public function actionArticleUpdate($id)
    {
        $model=$this->loadModel($id);
        $model->scenario = 'article';

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Reply']))
        {
            $model->attributes=$_POST['Reply'];
            if($model->save())
            {
                $this->redirect(array('view','id'=>$model->id));
            }                
        }

        $this->render('articleUpdate',array(
            'model'=>$model,
        ));
    }

    /**
    * Deletes a particular model.
    * If deletion is successful, the browser will be redirected to the 'admin' page.
    * @param integer $id the ID of the model to be deleted
    */
    public function actionDelete($id)
    {
        if(Yii::app()->request->isPostRequest)
        {
            // we only allow deletion via POST request
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if(!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
        }
        else
            throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
    }

    /**
    * Manages all models.
    */
    public function actionIndex()
    {
        $model=new Reply('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['Reply']))
            $model->attributes=$_GET['Reply'];

        $this->render('index',array(
            'model'=>$model,
        ));
    }

    /**
    * Returns the data model based on the primary key given in the GET variable.
    * If the data model is not found, an HTTP exception will be raised.
    * @param integer the ID of the model to be loaded
    */
    public function loadModel($id)
    {
        $model=Reply::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    /**
    * Performs the AJAX validation.
    * @param CModel the model to be validated
    */
    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']) && $_POST['ajax']==='reply-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }


    public function actionSetting()
    {
        $model=new ReplySettingForm;

        if(isset($_POST['ReplySettingForm']))
        {
            $model->attributes=$_POST['ReplySettingForm'];
            if($model->save()){
                Yii::app()->user->setFlash('success', '保存成功');
            }
        }

        $model->attributes=Yii::app()->settings->get('system');

        $this->render('setting',array(
            'model'=>$model,
        ));
    }
}

protected/modules/admin/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('/layouts/main'); ?>
<div class="container">
    <?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/modules/admin/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('/layouts/main'); ?>
<div class="container">
    <div class="row">
        <div class="col-sm-3 col-xs-12">
            <ul class="nav">
                <?php foreach ($this->menu as $menu) { ?>
                    <li><?php echo CHtml::link($menu['label'], $menu['url']) ?></li>
                <?php } ?>
            </ul>
        </div>
        <div class="col-sm-9 col-xs-12">
            <?php echo $content; ?>
        </div>
    </div>
</div>
<?php $this->endContent(); ?>

protected/modules/admin/views/layouts/main.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="language" content="en"/>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title><?php echo CHtml::encode($this->pageTitle); ?></title>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="/js/common.js"></script>
</head>
<body>
    <?php
    $admin = Admin::model()->findByPk(Yii::app()->adminUser->id);

    if($admin)
    {
        $auths = $admin->adminGroup->menu;
        $auths = explode(',', $auths);

        $navs = array();

        $navs[] = array('label' => '首页', 'url' => array('/admin/default/index'));

        if(array_search('adminGroup', $auths)!==false || array_search('admin', $auths)!==false){
            $menu = array(
                'class' => 'booster.widgets.TbMenu',
                'type' => 'navbar',
                'url'=>'#',
                'label'=>'管理员',
                'active' => in_array(Yii::app()->controller->id, array('adminGroup', 'admins')),
                'items' => array()
            );

            $items = array();
            if(array_search('adminGroup', $auths)!==false){
                $items[] = array('label' => '管理员分组', 'url' => array('adminGroup/'));
            }
            if(array_search('admins', $auths)!==false){
                $items[] = array('label' => '管理员', 'url' => array('admins/'));
            }
            $menu['items'] = $items;
            $navs[] = $menu;
        }

        if(array_search('group', $auths)!==false || array_search('user', $auths)!==false){
            $menu = array(
                'class' => 'booster.widgets.TbMenu',
                'type' => 'navbar',
                'url'=>'#',
                'label'=>'用户',
                'active' => in_array(Yii::app()->controller->id, array('group', 'user')),
                'items' => array()
            );

            $items = array();
            if(array_search('group', $auths)!==false){
                $items[] = array('label' => '用户分组', 'url' => array('group/'));
            }
            if(array_search('user', $auths)!==false){
                $items[] = array('label' => '用户', 'url' => array('user/'));
            }
            $menu['items'] = $items;
            $navs[] = $menu;
        }

        if(array_search('dealer', $auths)!==false){
            $navs[] = array('label' => '渠道', 'url' => array('/admin/dealer/index'));
        }

        if(array_search('display', $auths)!==false){
            $navs[] = array('label' => '示范展示', 'url' => array('/admin/display/index'));
        }

        if(array_search('reply', $auths)!==false){
            $navs[] = array(
                'class' => 'booster.widgets.TbMenu',
                'type' => 'navbar',
                'url'=>'#',
                'label'=>'自动回复',
                'active' => in_array(Yii::app()->controller->id, array('reply')),
                'items' => array(
                    array('label' => '自动回复', 'url' => array('reply/')),
                    array('label' => '回复设置', 'url' => array('reply/setting')),
                )
            );
        }

        if(array_search('menu', $auths)!==false){
            $navs[] = array('label' => '自定义菜单', 'url' => array('/admin/menu/'));
        }

        $navs = array(array(
            'class' => 'booster.widgets.TbMenu',
            'type' => 'navbar',
            'items' => $navs,
        ));

        $navs[] = array(
            'class' => 'booster.widgets.TbMenu',
            'type' => 'navbar',
            'htmlOptions' => array('class' => 'pull-right'),
            'items' => array(
                array('label'=>'注销 ('.Yii::app()->adminUser->name.')', 'url'=>array('/admin/site/logout'), 'visible'=>!Yii::app()->adminUser->isGuest)
            )
        );
    }else{
       $navs = array(); 
    }
    ?>

    <?php
        $this->widget(
            'booster.widgets.TbNavbar',
            array(
                'brand' => CHtml::encode(Yii::app()->name),
                'fixed' => false,
                'fluid' => false,
                'items' => $navs,
            )
        );
    ?>
    
    <?php if(isset($this->breadcrumbs)):?>
    <div class="container">
        <?php $this->widget('booster.widgets.TbBreadcrumbs', array(
            'homeLink'=>CHtml::link('首页', array('/admin/')),
            'links'=>$this->breadcrumbs,
        )); ?><!-- breadcrumbs -->
    </div>
    <?php endif?>

    <div class="container">
        <?php
            foreach(Yii::app()->user->getFlashes() as $key => $message) {
                $key = $key=='error'?'danger':$key;
                echo '<div class="alert alert-' . $key . '">' . $message . "</div>\n";
            }
        ?>
    </div>

    <?php echo $content; ?>

    <footer class="footer">
        <div class="container">
            <p class="powered">
                Copyright &copy; 2014 by <?php echo CHtml::encode(Yii::app()->name); ?> </p>
        </div>
    </footer>
</body>
</html>