protected/modules/admin/controllers/ArticleController.php
<?php

class ArticleController extends AdminController
{
    /**
    * @return array action filters
    */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
    * Specifies the access control rules.
    * This method is used by the 'accessControl' filter.
    * @return array access control rules
    */
    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('*'),
                'users'=>array('admin'),
            ),
        );
    }

    /**
    * Displays a particular model.
    * @param integer $id the ID of the model to be displayed
    */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }

    /**
    * Creates a new model.
    * If creation is successful, the browser will be redirected to the 'view' page.
    */
    public function actionCreate($id)
    {
        $model=new Article('create');

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Article']))
        {
            $model->attributes=$_POST['Article'];
            $model->replyId = $id;
            if($model->save())
            {
                $this->redirect(array('reply/view','id'=>$id));
            }
        }

        $reply = Reply::model()->findByPk($id);

        if(sizeof($reply->articles)>9){
            $this->setFlash('error', '一个回复最多只能10篇文章');
            $this->redirect(array('reply/view','id'=>$id));
        }

        $this->render('create',array(
            'model'=>$model,
            'reply'=>$reply
        ));
    }

    /**
    * Updates a particular model.
    * If update is successful, the browser will be redirected to the 'view' page.
    * @param integer $id the ID of the model to be updated
    */
    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Article']))
        {
            $model->attributes=$_POST['Article'];
            if($model->validate())
            {
                if($model->cover)
                {
                    $model->save();
                }
                $this->redirect(array('reply/view','id'=>$model->replyId));
            }
        }

        $this->render('update',array(
            'model'=>$model,
        ));
    }

    /**
    * Deletes a particular model.
    * If deletion is successful, the browser will be redirected to the 'admin' page.
    * @param integer $id the ID of the model to be deleted
    */
    public function actionDelete($id)
    {
        // if(Yii::app()->request->isPostRequest)
        // {
            // we only allow deletion via POST request
            $model = $this->loadModel($id);
            $model->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if(!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('reply/view', 'id'=>$model->replyId));
        // }
        // else
        //     throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
    }

    /**
    * Manages all models.
    */
    public function actionIndex($id)
    {
        $model=new Article('search');
        $model->unsetAttributes();  // clear any default values
        $model->replyId = $id;
        if(isset($_GET['Article']))
        {
            $model->attributes=$_GET['Article'];
        }

        $reply = Reply::model()->findByPk($id);
        $this->render('index',array(
            'model'=>$model,
            'reply'=>$reply,
        ));
    }

    /**
    * Returns the data model based on the primary key given in the GET variable.
    * If the data model is not found, an HTTP exception will be raised.
    * @param integer the ID of the model to be loaded
    */
    public function loadModel($id)
    {
        $model=Article::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    /**
    * Performs the AJAX validation.
    * @param CModel the model to be validated
    */
    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']) && $_POST['ajax']==='article-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/modules/admin/controllers/ReplyController.php
<?php

class ReplyController extends AdminController
{

    /**
    * Displays a particular model.
    * @param integer $id the ID of the model to be displayed
    */
    public function actionView($id)
    {
        $model = $this->loadModel($id);
        if($model->type==Reply::TYPE_NEWS){
            $this->redirect(array('articleView', 'id'=>$id));
        }

        $this->render('view',array(
            'model'=>$model,
        ));
    }

    /**
    * Displays a particular model.
    * @param integer $id the ID of the model to be displayed
    */
    public function actionArticleView($id)
    {
        $this->render('articleView',array(
            'model'=>$this->loadModel($id),
        ));
    }

    /**
    * Creates a new model.
    * If creation is successful, the browser will be redirected to the 'view' page.
    */
    public function actionArticleCreate()
    {
        $model=new Reply('article');

        if(isset($_POST['Reply']))
        {
            $model->attributes=$_POST['Reply'];
            $model->type = Reply::TYPE_NEWS;
            if($model->save())
            {
                $this->redirect(array('articleView','id'=>$model->id));
            }
        }

        $this->render('articleCreate',array(
            'model'=>$model,
        ));
    }

    /**
    * Creates a new model.
    * If creation is successful, the browser will be redirected to the 'view' page.
    */
    public function actionCreate()
    {
        $model=new Reply();

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Reply']))
        {
            $model->attributes=$_POST['Reply'];
            if($model->save())
                $this->redirect(array('view','id'=>$model->id));
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    }

    /**
    * Updates a particular model.
    * If update is successful, the browser will be redirected to the 'view' page.
    * @param integer $id the ID of the model to be updated
    */
    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);

        if($model->type==Reply::TYPE_NEWS){
            $this->redirect(array('articleUpdate', 'id'=>$id));
        }

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Reply']))
        {
            $model->attributes=$_POST['Reply'];
            if($model->save())
            {
                $this->redirect(array('view','id'=>$model->id));
            }
        }

        $this->render('update',array(
            'model'=>$model,
        ));
    }

    /**
    * Updates a particular model.
    * If update is successful, the browser will be redirected to the 'view' page.
    * @param integer $id the ID of the model to be updated
    */
    public function actionArticleUpdate($id)
    {
        $model=$this->loadModel($id);
        $model->scenario = 'article';

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Reply']))
        {
            $model->attributes=$_POST['Reply'];
            if($model->save())
            {
                $this->redirect(array('view','id'=>$model->id));
            }                
        }

        $this->render('articleUpdate',array(
            'model'=>$model,
        ));
    }

    /**
    * Deletes a particular model.
    * If deletion is successful, the browser will be redirected to the 'admin' page.
    * @param integer $id the ID of the model to be deleted
    */
    public function actionDelete($id)
    {
        if(Yii::app()->request->isPostRequest)
        {
            // we only allow deletion via POST request
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if(!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
        }
        else
            throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
    }

    /**
    * Manages all models.
    */
    public function actionIndex()
    {
        $model=new Reply('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['Reply']))
            $model->attributes=$_GET['Reply'];

        $this->render('index',array(
            'model'=>$model,
        ));
    }

    /**
    * Returns the data model based on the primary key given in the GET variable.
    * If the data model is not found, an HTTP exception will be raised.
    * @param integer the ID of the model to be loaded
    */
    public function loadModel($id)
    {
        $model=Reply::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    /**
    * Performs the AJAX validation.
    * @param CModel the model to be validated
    */
    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']) && $_POST['ajax']==='reply-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }


    public function actionSetting()
    {
        $model=new ReplySettingForm;

        if(isset($_POST['ReplySettingForm']))
        {
            $model->attributes=$_POST['ReplySettingForm'];
            if($model->save()){
                Yii::app()->user->setFlash('success', '保存成功');
            }
        }

        $model->attributes=Yii::app()->settings->get('system');

        $this->render('setting',array(
            'model'=>$model,
        ));
    }
}

protected/modules/admin/views/reply/_articleForm.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
    'id'=>'reply-form',
    'enableAjaxValidation'=>false,
    'type'=>'horizontal',
    'enableClientValidation'=>true,
    'clientOptions'=>array(
        'validateOnSubmit'=>true
    ),
    'htmlOptions'=>array(
        'enctype'=>'multipart/form-data'
    )
)); ?>

<p class="help-block">带 <span class="required">*</span> 必填.</p>

<?php echo $form->errorSummary($model); ?>

    <?php echo $form->textFieldGroup($model,'name',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

    <?php echo $form->textFieldGroup($model,'keywords',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

    <?php echo $form->textFieldGroup($model,'title', array('widgetOptions'=>array('htmlOptions'=>array('rows'=>6, 'cols'=>50, 'class'=>'span8')))); ?>

    <?php echo $form->hiddenField($model,'cover'); ?>

    <div class="form-group">
        <label class="col-sm-3 control-label required" for="Reply_description">封面<span class="required">*</span></label>
        <div class="col-sm-9">
            <div id="uploader-demo">
                <!--用来存放item-->
                <div id="fileList" class="uploader-list">
                    <?php if($model->cover){echo CHtml::image($model->cover, '', array('width'=>'320'));} ?>
                </div>
                <div id="filePicker">选择图片</div>
                <div class="hint">封面（大图片建议尺寸：360像素 * 200像素）</div>
            </div>
        </div>
    </div>

    <?php echo $form->textAreaGroup($model,'description', array('widgetOptions'=>array('htmlOptions'=>array('rows'=>6, 'cols'=>50, 'class'=>'span8')))); ?>

    <div class="form-group">
        <div class="col-sm-3 control-label required">内容<span class="required">*</span></div>
        <div class="col-sm-9">
            <script id="editor" name="Reply[content]" type="text/plain"><?php echo $model->content ?></script>
        </div>
    </div>

    <?php
    $this->widget('ext.ueditor.UeditorWidget',
            array(
                'id'=>'editor',//页面中输入框（或其他初始化容器）的ID
                'name'=>'editor',//指定ueditor实例的名称,个页面有多个ueditor实例时使用
            )
        );
    ?>

<div class="form-actions">
    <?php $this->widget('booster.widgets.TbButton', array(
            'buttonType'=>'submit',
            'context'=>'primary',
            'label'=>$model->isNewRecord ? '创建' : '更新',
        )); ?>
</div>

<?php $this->endWidget(); ?>

<link rel="stylesheet" type="text/css" href="/css/webuploader.css">
<script type="text/javascript" src="/js/webuploader/webuploader.js"></script>
<script type="text/javascript">
var uploader = WebUploader.create({
    // 选完文件后，是否自动上传。
    auto: true,

    // swf文件路径
    swf: '/swf/Uploader.swf',

    // 文件接收服务端。
    server: '/file/upload',

    // 选择文件的按钮。可选。
    // 内部根据当前运行是创建，可能是input元素，也可能是flash.
    pick: '#filePicker',

    // 只允许选择图片文件。
    accept: {
        title: 'Images',
        extensions: 'gif,jpg,jpeg,bmp,png',
        mimeTypes: 'image/*'
    }
});

uploader.on( 'fileQueued', function( file ) {
    // $list为容器jQuery实例
    $img = $('.uploader-list').html('<img />').find('img');

    // 创建缩略图
    // 如果为非图片文件，可以不用调用此方法。
    // thumbnailWidth x thumbnailHeight 为 100 x 100
    uploader.makeThumb( file, function( error, src ) {
        if ( error ) {
            $img.replaceWith('<span>不能预览</span>');
            return;
        }

        $img.attr( 'src', src );
    }, 320, 280 );
});

uploader.on( 'uploadAccept', function(object, ret) {
    $('#Reply_cover').val(ret.url);
});
</script>

protected/modules/admin/views/reply/_form.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'id'=>'reply-form',
	'enableAjaxValidation'=>false,
	'type'=>'horizontal',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true
	),
)); ?>

<p class="help-block">带 <span class="required">*</span> 必填.</p>

<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldGroup($model,'name',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

	<?php echo $form->textFieldGroup($model,'keywords',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

	<?php echo $form->textAreaGroup($model,'content', array('widgetOptions'=>array('htmlOptions'=>array('rows'=>6, 'cols'=>50, 'class'=>'span8')))); ?>

<div class="form-actions">
	<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'submit',
			'context'=>'primary',
			'label'=>$model->isNewRecord ? '创建' : '更新',
		)); ?>
</div>

<?php $this->endWidget(); ?>

protected/modules/admin/views/reply/_search.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>
		<?php echo $form->textFieldGroup($model,'name',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

	<div class="form-actions">
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType' => 'submit',
			'context'=>'primary',
			'label'=>'搜索',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/modules/admin/views/reply/articleCreate.php
<?php
$this->pageTitle = Yii::t('models', 'models.Reply') . '管理-' . $this->pageTitle;
$this->breadcrumbs=array(
    Yii::t('models', 'models.Reply')=>array('index'),
    '创建',
);
?>

<h1>创建图文<?php echo Yii::t('models', 'models.Reply') ?></h1>

<?php echo $this->renderPartial('_articleForm', array('model'=>$model)); ?>

protected/modules/admin/views/reply/articleUpdate.php
<?php
$this->pageTitle = Yii::t('models', 'models.Reply') . '管理-' . $this->pageTitle;
$this->breadcrumbs=array(
    Yii::t('models', 'models.Reply')=>array('index'),
    $model->name=>array('view','id'=>$model->id),
    '更新',
);
?>

<h1>更新图文<?php echo Yii::t('models', 'models.Reply') ?></h1>

<?php echo $this->renderPartial('_articleForm', array('model'=>$model)); ?>

protected/modules/admin/views/reply/articleView.php
<?php
$this->pageTitle = Yii::t('models', 'models.Reply') . '管理-' . $this->pageTitle;
$this->breadcrumbs=array(
    Yii::t('models', 'models.Reply')=>array('index'),
    $model->name,
);
?>

<h1>查看<?php echo Yii::t('models', 'models.Reply') ?></h1>

<?php $this->widget('booster.widgets.TbDetailView',array(
'data'=>$model,
'attributes'=>array(
        'id',
        'name',
        'keywords',
        'title',
        'description',
        array(
            'name'=>'cover',
            'type'=>'raw',
            'value'=>CHtml::image($model->cover)
        ),
        array(
            'name'=>'content',
            'type'=>'raw'
        ),

        'createTime',
        'updateTime',
),
)); ?>

<?php echo CHtml::link('<i class="glyphicon glyphicon-plus"></i>创建文章', array('article/create', 'id'=>$model->id), array('class'=>'btn btn-primary')) ?><br/>


<table class="table">
    <thead>
        <tr>
            <td>标题</td>
            <td>封面</td>
            <td>描述</td>
            <td>创建时间</td>
            <td>操作</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($model->articles as $article) { ?>
        <tr>
            <td><?php echo $article->title ?></td>
            <td><?php echo CHtml::image($article->cover, '', array('width'=>300)) ?></td>
            <td><?php echo $article->description ?></td>
            <td><?php echo $article->createTime ?></td>
            <td>
                <?php 
                echo CHtml::link('<i class="glyphicon glyphicon-eye-open"></i>', array('article/view', 'id'=>$article->id), array('title'=>'查看'));
                echo CHtml::link('<i class="glyphicon glyphicon-pencil"></i>', array('article/update', 'id'=>$article->id), array('title'=>'更新'));
                echo CHtml::link('<i class="glyphicon glyphicon-trash"></i>', array('article/delete', 'id'=>$article->id), array('title'=>'删除'));
                ?>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>

protected/modules/admin/views/reply/create.php
<?php
$this->pageTitle = Yii::t('models', 'models.Reply') . '管理-' . $this->pageTitle;
$this->breadcrumbs=array(
	Yii::t('models', 'models.Reply')=>array('index'),
	'创建',
);
?>

<h1>创建<?php echo Yii::t('models', 'models.Reply') ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/admin/views/reply/index.php
<?php
$this->pageTitle = Yii::t('models', 'models.Reply') . '管理-' . $this->pageTitle;
$this->breadcrumbs=array(
    Yii::t('models', 'models.Reply')=>array('index'),
    '管理',
);

Yii::app()->clientScript->registerScript('search', "
    $('.search-button').click(function(){
        $('.search-form').toggle();
        return false;
    });
    $('.search-form form').submit(function(){
        $.fn.yiiGridView.update('reply-grid', {
            data: $(this).serialize()
        });
        return false;
    });
");
?>

<h1><?php echo Yii::t('models', 'models.Reply') ?>管理</h1>

<?php echo CHtml::link('<i class="glyphicon glyphicon-plus"></i>创建文字'.Yii::t('models', 'models.Reply'), array('create'), array('class'=>'btn btn-primary')) ?>&nbsp;&nbsp;&nbsp;&nbsp;
<?php echo CHtml::link('<i class="glyphicon glyphicon-plus"></i>创建图文'.Yii::t('models', 'models.Reply'), array('articleCreate'), array('class'=>'btn btn-primary')) ?><br/>
<?php echo CHtml::link('高级搜索','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
    <?php $this->renderPartial('_search',array(
        'model'=>$model,
    )); ?>
</div><!-- search-form -->

<?php $this->widget('booster.widgets.TbGridView',array(
    'id'=>'reply-grid',
    'dataProvider'=>$model->search(),
    'filter'=>$model,
    'columns'=>array(
        'id',
		'name',
        'keywords',
        array(
            'name'=>'type',
            'value'=>'Reply::$types[$data->type]',
            'filter'=>CHtml::activeDropDownList($model, 'type', Reply::$types, array(
                'class'=>'form-control',
                'empty'=>'请选择'
            )),
            'htmlOptions'=>array('width'=>100),
        ),
		'createTime',
        array(
            'class'=>'booster.widgets.TbButtonColumn',
            // 'template'=>'{view} {update} {delete}',
            // 'buttons'=>array(
            //     'confirm'=>array(
            //         'label'=>'文章',
            //         'url'=>"Yii::app()->createUrl('admin/user/confirm', array('id'=>\$data->id))",
            //         'visible'=>'$data->status==User::STATUS_APPLY',
            //         'click'=>'function(){return confirm("你确认同意吗？")}',
            //     ),
            // )
        ),
    ),
)); ?>

protected/modules/admin/views/reply/setting.php
<?php
$this->pageTitle = '自动回复设置-' . $this->pageTitle;
$this->breadcrumbs=array(
    Yii::t('models', 'models.Reply')=>array('index'),
    '设置',
);
?>

<h1><?php echo Yii::t('models', 'models.Reply') ?>设置</h1>

<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
    'id'=>'school-form',
    'enableAjaxValidation'=>false,
    'type'=>'horizontal',
    'enableClientValidation'=>true,
    'clientOptions'=>array(
        'validateOnSubmit'=>true
    ),
)); ?>

<p class="help-block">带 <span class="required">*</span> 必填.</p>

<?php echo $form->errorSummary($model); ?>

    <?php echo $form->textFieldGroup($model,'defaultReply',array(
        'widgetOptions'=>array(
            'htmlOptions'=>array(
                'class'=>'span5',
                'maxlength'=>255,
                'placeholder'=>'可根据关键字直接关联指定的回复规则'
            )
        ),
        'hint'=>'当系统不知道该如何回复粉丝的消息时，默认发送的内容。
指定系统不知道该如何回复粉丝的消息时，发送的默认信息, 你可以在这里输入关键字, 那么系统不知道该如何回复粉丝的消息时就相当于发送这个内容至微擎系统
这个过程是程序模拟的, 比如这里添加关键字: ￥@%&%#@*, 系统不知道该如何回复粉丝的消息, 微擎系统相当于接受了粉丝用户的消息, 内容为"欢迎关注"'
    )); ?>

    <?php echo $form->textFieldGroup($model,'welcomeReply',array(
        'widgetOptions'=>array(
            'htmlOptions'=>array(
                'class'=>'span5',
                'maxlength'=>255,
                'placeholder'=>'可根据关键字直接关联指定的回复规则'
            )
        ),
        'hint'=>'设置用户添加公众帐号好友时，发送的欢迎信息。 表情
指定用户添加公众帐号好友时，发送的欢迎信息, 你可以在这里输入关键字, 那么用户添加公众号好友时就相当于发送这个内容至微擎系统
这个过程是程序模拟的, 比如这里添加关键字: 欢迎关注, 那么用户添加公众号好友时, 微擎系统相当于接受了粉丝用户的消息, 内容为"欢迎关注"'
    )); ?>

<div class="form-actions">
    <?php $this->widget('booster.widgets.TbButton', array(
            'buttonType'=>'submit',
            'context'=>'primary',
            'label'=>'保存',
        )); ?>
</div>

<?php $this->endWidget(); ?>

protected/modules/admin/views/reply/update.php
<?php
$this->pageTitle = Yii::t('models', 'models.Reply') . '管理-' . $this->pageTitle;
$this->breadcrumbs=array(
	Yii::t('models', 'models.Reply')=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'更新',
);
?>

<h1>更新<?php echo Yii::t('models', 'models.Reply') ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/modules/admin/views/reply/view.php
<?php
$this->pageTitle = Yii::t('models', 'models.Reply') . '管理-' . $this->pageTitle;
$this->breadcrumbs=array(
    Yii::t('models', 'models.Reply')=>array('index'),
    $model->name,
);
?>

<h1>查看<?php echo Yii::t('models', 'models.Reply') ?></h1>

<?php $this->widget('booster.widgets.TbDetailView',array(
'data'=>$model,
'attributes'=>array(
        'id',
        'name',
        'keywords',
        'content',
        'createTime',
        'updateTime',
),
)); ?>